---
label: Global Site Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: select
    name: layout_style
    label: Layout Style
    description: The style of the theme layout
    default: grid
    config:
      source:
        type: custom
      options:
        - grid
        - list
  - type: select
    name: palette
    label: Color Palette
    description: The color palette of the theme.
    default: green
    config:
      source:
        type: custom
      options:
        - green
        - blue
        - black
        - red
  - type: field_group
    name: header
    label: Header Configuration
    fields:
      - type: text
        name: title
        label: Header Title
        description: The title displayed in the header if no logo image added.
      - type: file
        name: logo_img
        label: Logo
        description: The logo image displayed in the header.
      - type: boolean
        name: has_nav
        label: Enable Navigation Menu
        description: Display the navigation menu bar in the header.
        default: true
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
      - type: text
        name: content
        label: Footer Content
        description: The copyright text displayed in the footer.
      - type: field_group_list
        name: links
        label: Links
        description: A list of links displayed in the footer.
        fields:
          - type: text
            name: text
            label: Link text
          - type: text
            name: url
            label: URL
          - type: boolean
            name: new_window
            label: Open in new window
            default: true
        config:
          labelField: text
      - type: boolean
        name: has_social
        label: Enable Social Links
        description: Display social links in the footer.
        default: true
